[package]
name = "bevy_joycons"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy_input = { version = "0.9.1", default-features = false }
joycon = { git = "https://github.com/Yamakaky/joy", version = "0.1.0", rev = "c55030e" }
